export const SET_PLAYERS="SET_PLAYERS"
export const SET_MATCH="SET_MATCH"
export const CLEAR_STATE='CLEAR_STATE'

export const TOGGLE_PLAYERS='TOGGLE_PLAYERS'
export const TOGGLE_MATCH='TOGGLE_MATCH'
export const TOGGLE_HEROES='TOGGLE_HEROES'

export const SET_ALL_HEROES='SET_ALL_HEROES'
export const SORT_PRO_BY_WINRATE='SET_PRO_BY_WINRATE'
export const SET_ITEMS='SET_ITEMS'
export const SET_ITEMS_IDS='SET_ITEMS_IDS'

export const SET_PATCHNOTES='SET_PATCHNOTES'

export const SET_PLAYER='SET_PLAYER'
export const SET_WL='SET_WL'
export const SET_RECENT_MATCHES='SET_RECENT_MATCHES'
export const SET_ALL_MATCHES='SET_ALL_MATCHES'
export const SET_PLAYED_HEROES='SET_PLAYED_HEROES'
export const SET_PEERS='SET_PEERS'

export const SET_ABILITIES='SET_ABILITIES'
export const SET_ABILITIES_IDS='SET_ABILITIES_IDS'
export const SET_ABILITIES_N_TALENTS='SET_ABILITIES_N_TALENTS'

export const SET_MATCHES='SET_MATCHES'
export const SET_MATCHUPS='SET_MUTCHUPS'
export const SET_DURATIONS='SET_DURATIONS'
export const SET_HERO_PLAYERS='SET_HERO_PLAYERS'
export const SET_ITEM_POPULARITY='SET_ITEM_POPULARITY'

export const SET_TEAMS = 'SET_TEAMS'

export const SET_TEAM = 'SET_TEAM'
export const SET_TEAM_MATCHES = 'SET_TEAM_MATCHES'
export const SET_TEAM_PLAYERS = 'SET_TEAM_PLAYERS'
export const SET_TEAM_HEROES = 'SET_TEAM_HEROES'


